# Basic Formatting
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Max"

# Imports
reorder_imports = true

# Control Flow
remove_nested_parens = true

# Match & Other Expressions
match_block_trailing_comma = true
match_arm_leading_pipes = "Never"

# Chains
chain_width = 60

# Modules
merge_derives = true

# Use Statements
use_field_init_shorthand = true
